# put your secret values and credentials here. do not share this file and do not push it to github
[sources.rest_api]
github_token = "github_token" # please set me up!

[destination.lancedb]
embedding_model_provider = "cohere"
embedding_model = "embed-english-v3.0"
[destination.lancedb.credentials]
uri = ".lancedb"
api_key = "api_key" # please set me up!
embedding_model_provider_api_key = "embedding_model_provider_api_key" # please set me up!
